extends Node
var eventID
var eventDescription
var eventChoice1
var eventChoice2
var consequences

# Called when the node enters the scene tree for the first time.
func _ready():
	var growthconserveproto = [0, "It’s the beginning of the water year, and with it comes the choice of optimization. A couple of Farmechs have pitched a couple of differing ideas for improving the Ampear harvest. One Farmech says that they need to expand the farmland since they’re reaching the maximum capacity on the number of crops that could be planted. The other insists that they must enter a fallow period, in which they don’t plant anything for a period to allow the soil a chance to recover. Thus, the choice is turned over to you as their superior.", "Expand the Orchards", "Fallow the Soil"]
	var gutterproto = [1, "It’s the beginning of the water year, and with it comes the opportunity to designate new priorities. Your team of Research-Rs have come up with a project that’d make the mountain more efficient in providing runoff into the water reservoir. It’ll involve either shaping the mountain into a more controlled stream of water or building a gutter to transport the water safely. Which do you think would be better?", "Terraform the Mountain", "Construct the Gutter"]
	var devproto = [2, "It’s the beginning of the water year, and with it comes the perfect time to increase productivity. This cycle, you have already made plans to help expedite the process of constructing the beacon. You had two primary directives already put to paper during the last year, so now is the time to choose. One plan involves rapidly producing more Olmechas to increase the productivity of all projects, while the other involves digging into the exterior of the mountain to glean more metal. It’s your call.", "Mass Production", "Heightened Mining"]
	var beaconp1 = [3, "After assessing your current status, you realized it’s high time to begin working on the Pioneer Initiative’s end goal: the construction of the Beacon. This project will take multiple years to complete, but starting now will help progress that further. You’ll have to start by clearing a sufficient amount of earth to make the base of the beacon. Do you wish to begin?", "Begin Construction", "Delay Construction"]
	var infestation = [4, "An alarming discovery has been made: there’s been a large influx of native bug species desecrating your Ampear orchards! Luckily, some of your Research-Rs have developed a very potent anti-pest solution, but they’re uncertain of how it would affect the environment due to a lack of testing. You can always have the Farmechas manually gun down the bugs, but you’ll likely lose some in the process regardless. What do you think?", "Use Pesticides", "Manual Removal"]
	var lubristart = [5, "After a quick look through your blueprint database, you’ve decided that if you are going to build any of these factories, you’ll probably create the Lubricant Synthesizer. It increases production, but it’ll take some time to fully realize and metal to complete.", "Begin Construction", "Delay Construction"]
	var earthquake = [6, "Outside your office, you suddenly hear a large rumbling noise. You look out the window, and there are cracks in the ground snaking towards your structures! After doing some quick calculations, you deduce that the orchards and the mines are likely to be damaged by this disaster. What do you do?", "Prioritize Ampear Trees", "Prioritize Metal Mines"]
	var springstart = [7, "After a section of the mountain wall caved in during mining, a group of Mine-Rs have found an underwater reservoir! You’ll have to dig out tunnels leading to the primary water processing plant, but you’ll get a pretty big boost in water!", "Develop Reservoir", "Leave it Be"]
	var landslide = [8, "Outside your office, you suddenly hear a large rumbling noise. You look out the window, and there are boulders from the mountains barreling towards your orchards! After doing some quick calculations, you deduce that you can mitigate damage to the orchards, but there’s a high chance of damaged robots being the outcome of this disaster. What do you do?", "Protect the Orchards", "Protect the People"]
	var polluted = [9, "After a frantic message from a Research-R, you made a quick trip to the water processing plant. What you find there shocks you. The water is almost brown! Apparently there’s been a buildup in pollution in the entire reservoir, that’s been happening right under your nose. There’s solutions, but none of them are cheap.", "Overclock Cleansing", "Flush out Impurities"]
	var lubrisynth = [10, "Your Lubricant Synthesis project has been completed! Now you can get a lot more productivity out of each bot. Now that you notice it though, the factory is a little dangerously close to the stream…", "Begin Production", "Delay Production"]
	var lubrichange = [11, "Now that the Lubricant Synthesizer has been active for a few seasons, you’ve taken steps to increase the potential productivity of the factory. Now that those preparations are complete, you find yourself contemplating how this’d e=affect the environment…", "Ramp Production", "Cease Production"]
	var beaconp2 = [12, "After assessing your current status, you realized it’s high time to continue working on the Pioneer Initiative’s end goal: the construction of the Beacon. This  time, you’ll have to contribute a lot of metal to continue construction. Do you wish to begin now?", "Begin Construction", "Delay Construction"]
	var beaconp3 = [13, "After assessing your current status, you realized it’s high time to continue working on the Pioneer Initiative’s end goal: the construction of the Beacon. This  time, you’ll have to mine out a significant portion of the mountain to extract the necessary minerals. Do you wish to begin now?", "Begin Construction", "Delay Construction"]
	var springleak = [14, "An emergency notification goes off in your office; it appears that the pipe connecting the underground reservoir to the water plant has broken down!", "Cut Off Flow", "Emergency Patching"]

# Called every frame. 'delta' is the elapsed time since the previous frame.
func _process(delta):
	pass
